[tool.poetry]
name = "topdf"
version = "0.1.0"
description = ""
authors = ["amzdll"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pypdf2 = "^3.0.1"
fastapi = "^0.109.0"
pypdf4 = "^1.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
